version: "3"

services:
  app:
    build: .
    environment:
      - DB_URL='postgre://${POSTGRES_USER}@postgres/${POSTGRES_DB}'
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}